# Generated by Django 3.2 on 2020-07-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='catagory',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catagory',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
